sudo: required
dist: trusty
language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
cache:
  apt: true
  pip: true
before_install:
- export ROS_DISTRO=indigo
- export ROS_CI_DESKTOP=`lsb_release -cs`
- export ROS_MASTER_URI=http://localhost:11311
notifications:
  email: false
  slack:
    secure: ltnk5sqQlUYSHKxsujbLcAeh7SI6TkJvq3KehiBqk9z3mtTUnMTaWWUDb7jalQhBKQ9txmmwoRBvajpS2r2CyHrKR5hgj4wGf4WGaA8Pipc+xajgZI/U1K0UBT0gWqD9dHGdnYEu3KI5L0XyE4RHtK/XMuVOhjghBcwNGgvoMS9zkOSHeNHhudJzDm4fepzbBv5rNQFzlZgPMRD1o4t7BFtlFXTc4fqn3JWHLI/IrXbXNnn6lyYktjjLtsQtckOuZhuPwTCiQ5CQvDoHN/XFFRucW0V/7fUfM9woHzulZ6rCCkhfS5jGDwiOo2SWyR/whX93/F48Yjy439boa2y5yFh0CkgCfN4Wev3VrwxyCZA4EYp2xL9p9BmI9V1If6GwK/hgNlcSGWndrAj0Jofjj2aeJ7nvNOPy9eB00A5GSM64IPo3IMUel8PREO1KwtHZ1UN7nSXyAllegxFY6ysSpXEdFt5+eN2/kSgPh+yE5Efm3P0w+FLTCi2sZcfNEqXml8zbVWDsdB8Gzu88OjsV4WgCk2hsva04mRSuQp56BtkVP5KEMu9fbLCL5NHTWmxMNW63Ck6bFAqtVFKN+M1Vwzui6qyJ6HZHVid65Po1lSXFgnFFOIat0bqKN8nYJJHYbFbv/ezUdFBUB+4DTyoviAj9y8sAlhRuzOGBWYHjsUY=
install:
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main"
  > /etc/apt/sources.list.d/ros-latest.list'
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq -y python-catkin-pkg python-catkin-tools python-rosdep
  python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros ros-$ROS_DISTRO-rosdoc-lite
- source /opt/ros/$ROS_DISTRO/setup.bash
- sudo rosdep init
- rosdep update
- mkdir -p ~/catkin_ws/src
- cd ..; mv robot_markers ~/catkin_ws/src
- cd ~/catkin_ws/src
- git clone https://github.com/jstnhuang/transform_graph.git
- cd ~/catkin_ws
- catkin init
- rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
script:
- catkin build
after_success:
- cd ~/catkin_ws/src/robot_markers
- rosdoc_lite .
